### ISSUE TITLE
bitmap logos for Teki with GUIs like WinBoard Interface, ChessGUI, Arena etc.

### ISSUE THREAD

**Issue by yellow-panther** [Mk-Chan/Teki#2]
Hello Manik,
cf. 6 logos created with http://photofiltre.free.fr/ and http://photoscape.org/ps/main/index.php
I informed Ron to remove Teki from Source Code Engine List because it contains now Linux, Windows versions
[Teki logos bitmap 130x65.zip](https://github.com/Mk-Chan/Teki/files/1426902/Teki.logos.bitmap.130x65.zip)

**Comment by Mk-Chan** [comment]
5th one is pretty nice
